on:
  push:
    branches:
    - $default-branch
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
      echo "{{ DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      IMAGE_NAME="bcinteractive/memcached"
      IMAGE_TAG="$(git rev-parse --short HEAD)"
      DOCKER_BUILDKIT=1 docker build --tag "${IMAGE_NAME}:${IMAGE_TAG}" .
      docker push "${IMAGE_NAME}:${IMAGE_TAG}"
